apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
    version: v1
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: vault
        image: hashicorp/vault:1.14.0
        imagePullPolicy: Always
        command: ['sh', '-ec', '/usr/local/bin/docker-entrypoint.sh vault server -dev']
        env:
          - name: VAULT_ADDR
            value: "http://0.0.0.0:8200"
          - name: VAULT_API_ADDR
            value: "http://0.0.0.0:8200"
          - name: SKIP_CHOWN
            value: "true"
          - name: SKIP_SETCAP
            value: "true"
          - name: VAULT_DEV_ROOT_TOKEN_ID
            value: root
          - name: VAULT_DEV_LISTEN_ADDRESS
            value: "[::]:8200"
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "500m"