apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    version: v1
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redis
    spec:
      serviceAccountName: redis
      automountServiceAccountToken: false
      containers:
      - name: redis
        image: redis:6.2-alpine
        imagePullPolicy: Always
        command: ['sh', '-c', "redis-server --save 20 1 --loglevel warning"]
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "500m"