apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-webapp-dev
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonleebaker/argo-examples
    targetRevision: HEAD
    path: helm-webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true