apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonleebaker/argo-applications
    targetRevision: HEAD
    path: apps/products-api
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true