{{ if .Values.deploy.redis }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonleebaker/argo-applications
    targetRevision: HEAD
    path: apps/redis
    helm:
      values: |-
        {{- toYaml .Values | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{ end }}